# Generated by Django 3.2.14 on 2022-08-12 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanças', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='gasto',
            field=models.FloatField(),
        ),
    ]
