# Generated by Django 3.2.14 on 2022-08-12 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanças', '0002_alter_cliente_gasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ultima_movimentacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
