# Generated by Django 3.2.14 on 2022-08-13 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanças', '0003_cliente_ultima_movimentacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='ultima_movimentacao',
        ),
    ]
