# Generated by Django 3.2.14 on 2022-08-13 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanças', '0004_remove_cliente_ultima_movimentacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name_plural': 'Clientes'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='Clientes'),
        ),
    ]
