# Generated by Django 3.2.14 on 2022-08-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanças', '0005_auto_20220813_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='gasto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
